### ISSUE TITLE
Build Failure on Linux since commit 136dd71

### ISSUE THREAD

**Issue by Sembiance** [claunia/DiscImageChef#845]
Starting with commit 136dd71 I am no longer able to build Aaru on my Linux system.

Gentoo Packages installed:
dev-dotnet/dotnet-sdk-bin `8.0.105`
dev-dotnet/dotnet-runtime-nugets `6.0.30` `7.0.19` `8.0.5`

Build command I use: `dotnet build --configuration Release ./Aaru/Aaru.csproj`

It works perfectly fine in any versions earlier than that commit, but after it I get the following errors (just a snippet):
```
/home/sembiance/Downloads/Aaru-136dd71ea46a4caf55b0a9d5470aa70ed109a83b/Aaru.Filters/Register.cs(46,40): error CS0535: 'Register' does not implement interface member 'IPluginRegister.RegisterChecksumPlugins(IServiceCollection)' [/home/sembiance/Downloads/Aaru-136dd71ea46a4caf55b0a9d5470aa70ed109a83b/Aaru.Filters/Aaru.Filters.csproj]
/home/sembiance/Downloads/Aaru-136dd71ea46a4caf55b0a9d5470aa70ed109a83b/Aaru.Filters/Register.cs(46,40): error CS0535: 'Register' does not implement interface member 'IPluginRegister.RegisterFilesystemPlugins(IServiceCollection)' [/home/sembiance/Downloads/Aaru-136dd71ea46a4caf55b0a9d5470aa70ed109a83b/Aaru.Filters/Aaru.Filters.csproj]
```

Attached is the full [build_log.txt](https://github.com/user-attachments/files/15949424/build_log.txt) from the latest checked in code 

Let me know if there is any other information or tests you'd like me to perform.

**Comment by claunia** [comment]
Update your .NET to 8.0.300. 

For some reason the generator fails if the committed version is newer than the installed SDK version, and we yet do not why (plus the error message is very uninformative).
